### ISSUE TITLE
Convert Centigrade to Fahrenheit option

### ISSUE THREAD

**Issue by Flawm** [samuele-mattiuzzo/atom-metaweather#10]
I'm sure I'm not the only American who would appreciate this feature!

It seems that their API doesn't support requesting Fahrenheit instead of Centigrade, so you'd have to do the conversion after receiving the data. Luckily, the formula is simple:

°F = °C \* 9/5 + 32

And in action:

°48F = *9C \* 9/5 + 32

**Comment by samuele-mattiuzzo** [comment]
Hei @Flawm glad to see somebody's starting to use this! Will squeeze this in asap!

**Comment by samuele-mattiuzzo** [comment]
Done and published! Thanks for the feedback!
