### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by liamnewmarch** [samuele-mattiuzzo/atom-metaweather#12]
I’m getting this after restarting Atom. Looking at the API response body, it looks like `wind_direction_compass` is no longer being exposed.

Atom generated blurb:

---

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-metaweather](https://github.com/samuele-mattiuzzo/atom-metaweather) package, v0.7.0
### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /Users/lnewmarch/.atom/packages/atom-metaweather/lib/atom-metaweather-format.coffee:51

TypeError: Cannot read property 'toLowerCase' of undefined
    at Format._formatWind (/Users/lnewmarch/.atom/packages/atom-metaweather/lib/atom-metaweather-format.coffee:51:44)
    at Format._formatAll (/Users/lnewmarch/.atom/packages/atom-metaweather/lib/atom-metaweather-format.coffee:81:15)
    at Format.get (/Users/lnewmarch/.atom/packages/atom-metaweather/lib/atom-metaweather-format.coffee:91:12)
    at status-bar-metaweather.MetaweatherView._formatOutput (/Users/lnewmarch/.atom/packages/atom-metaweather/lib/atom-metaweather-view.coffee:106:9)
    at status-bar-metaweather.MetaweatherView._writeData (/Users/lnewmarch/.atom/packages/atom-metaweather/lib/atom-metaweather-view.coffee:110:29)
```

**Comment by Flawm** [comment]
Getting this as well.

> [Enter steps to reproduce below:]
> 1. Launch atom
> 
> **Atom Version**: 1.4.0
> **System**: Ubuntu 15.10
> **Thrown From**: [atom-metaweather](https://github.com/samuele-mattiuzzo/atom-metaweather) package, v0.7.0
> 
> ### Stack Trace
> 
> Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
> 
> ```
> At /home//.atom/packages/atom-metaweather/lib/atom-metaweather-format.coffee:51
> 
> TypeError: Cannot read property 'toLowerCase' of undefined
>     at Format._formatWind (/home//.atom/packages/atom-metaweather/lib/atom-metaweather-format.coffee:51:44)
>     at Format._formatAll (/home//.atom/packages/atom-metaweather/lib/atom-metaweather-format.coffee:81:15)
>     at Format.get (/home//.atom/packages/atom-metaweather/lib/atom-metaweather-format.coffee:91:12)
>     at status-bar-metaweather.MetaweatherView._formatOutput (/home//.atom/packages/atom-metaweather/lib/atom-metaweather-view.coffee:106:9)
>     at status-bar-metaweather.MetaweatherView._writeData (/home//.atom/packages/atom-metaweather/lib/atom-metaweather-view.coffee:110:29)
>     at status-bar-metaweather.MetaweatherView.update (/home//.atom/packages/atom-metaweather/lib/atom-metaweather-view.coffee:128:6)
> ```
> 
> ### Commands
> 
> ```
> ```
> 
> ### Config
> 
> ``` json
> {
>   "core": {
>     "autoHideMenuBar": true,
>     "disabledPackages": [
>       "spell-check",
>       "wrap-guide",
>       "welcome",
>       "language-mustache",
>       "language-toml",
>       "link",
>       "update-package-dependencies",
>       "release-notes",
>       "about",
>       "autocomplete-atom-api",
>       "autoflow",
>       "encoding-selector",
>       "exception-reporting",
>       "image-view",
>       "language-clojure",
>       "language-csharp",
>       "language-gfm",
>       "language-git",
>       "language-go",
>       "language-hyperlink",
>       "language-java",
>       "language-less",
>       "language-perl",
>       "language-property-list",
>       "language-ruby",
>       "language-ruby-on-rails",
>       "language-sass",
>       "language-source",
>       "language-sql",
>       "language-text",
>       "language-xml",
>       "language-yaml",
>       "line-ending-selector",
>       "markdown-preview",
>       "metrics",
>       "open-on-github",
>       "package-generator",
>       "symbols-view",
>       "whitespace"
>     ],
>     "projectHome": "/home//projects/",
>     "themes": [
>       "one-dark-shade-ui",
>       "pop-rocks-syntax"
>     ]
>   },
>   "atom-metaweather": {
>     "location": 2487610,
>     "locationName": "SLC",
>     "showHumidity": true,
>     "showPredictability": true,
>     "showWind": true,
>     "temperatureMeasure": "F",
>     "updateTime": 15
>   }
> }
> ```
> 
> ### Installed Packages
> 
> ``` coffee
> # User
> atom-ctags, v4.4.2
> atom-metaweather, v0.7.0
> autocomplete-php, v0.3.7
> ctags-status, v1.3.4
> docblockr, v0.7.3
> file-type-icons, v0.7.4
> git-tab-status, v1.9.2
> language-smarty-php, v0.5.0
> linter, v1.11.3
> linter-php, v1.1.7
> minimap, v4.19.0
> minimap-git-diff, v4.1.8
> one-dark-shade-ui, v0.1.0
> pop-rocks-syntax, v0.2.0
> 
> # Dev
> No dev packages
> ```

**Comment by jasoncartwright** [comment]
API fixed. Sorry all.

**Comment by samuele-mattiuzzo** [comment]
Thanks JC! :D
