### ISSUE TITLE
Wind direction is wrong by 180 degrees

### ISSUE THREAD

**Issue by jasoncartwright** [samuele-mattiuzzo/atom-metaweather#8]
![screen shot 2015-12-07 at 14 57 20](https://cloud.githubusercontent.com/assets/763913/11629911/da44e138-9cf2-11e5-871e-07510d9636c2.png)

**Comment by samuele-mattiuzzo** [comment]
API response:

`[{"weather_state_name": "Light Cloud", "weather_state_abbr": "lc", "wind_direction_compass": "S", ...`

**Comment by jasoncartwright** [comment]
Wind direction is where the wind is coming from. I made this mistake :)

**Comment by samuele-mattiuzzo** [comment]
AH. I just checked on metaweather.com as well, html and source and all was flipped, so got confused. Basically all the arrows need updating with their counterpart. Thanks!

**Comment by samuele-mattiuzzo** [comment]
Closing since fixed and re-published
